//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transportes_3_capas_gen_7.CalculadoraServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CalculadoraServiceReference.CalculadoraServiceSoap")]
    public interface CalculadoraServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Suma", ReplyAction="*")]
        float Suma(float a, float b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Suma", ReplyAction="*")]
        System.Threading.Tasks.Task<float> SumaAsync(float a, float b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Resta", ReplyAction="*")]
        float Resta(float a, float b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Resta", ReplyAction="*")]
        System.Threading.Tasks.Task<float> RestaAsync(float a, float b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Multiplicacion", ReplyAction="*")]
        float Multiplicacion(float a, float b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Multiplicacion", ReplyAction="*")]
        System.Threading.Tasks.Task<float> MultiplicacionAsync(float a, float b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Division", ReplyAction="*")]
        float Division(float a, float b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Division", ReplyAction="*")]
        System.Threading.Tasks.Task<float> DivisionAsync(float a, float b);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CalculadoraServiceSoapChannel : Transportes_3_capas_gen_7.CalculadoraServiceReference.CalculadoraServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalculadoraServiceSoapClient : System.ServiceModel.ClientBase<Transportes_3_capas_gen_7.CalculadoraServiceReference.CalculadoraServiceSoap>, Transportes_3_capas_gen_7.CalculadoraServiceReference.CalculadoraServiceSoap {
        
        public CalculadoraServiceSoapClient() {
        }
        
        public CalculadoraServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalculadoraServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculadoraServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculadoraServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public float Suma(float a, float b) {
            return base.Channel.Suma(a, b);
        }
        
        public System.Threading.Tasks.Task<float> SumaAsync(float a, float b) {
            return base.Channel.SumaAsync(a, b);
        }
        
        public float Resta(float a, float b) {
            return base.Channel.Resta(a, b);
        }
        
        public System.Threading.Tasks.Task<float> RestaAsync(float a, float b) {
            return base.Channel.RestaAsync(a, b);
        }
        
        public float Multiplicacion(float a, float b) {
            return base.Channel.Multiplicacion(a, b);
        }
        
        public System.Threading.Tasks.Task<float> MultiplicacionAsync(float a, float b) {
            return base.Channel.MultiplicacionAsync(a, b);
        }
        
        public float Division(float a, float b) {
            return base.Channel.Division(a, b);
        }
        
        public System.Threading.Tasks.Task<float> DivisionAsync(float a, float b) {
            return base.Channel.DivisionAsync(a, b);
        }
    }
}
